version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181  # Changed port
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "32181:2181"  # Map the changed port

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181  # Use the changed port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092  # Changed port
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "39092:9092"  # Map the changed port
